// 200 anrop
const OK = 200;
const CREATED = 201;

// 400 anrop
const BAD_REQUEST = 400;
const UNAUTHORIZED = 401;
const FORBIDDEN = 403;
const NOT_FOUND = 404;
const METHOD_NOT_ALLOWED = 405;

// 500 anrop
const INTERNAL_SERVER_ERROR = 500;

export default {
  OK,
  CREATED,
  BAD_REQUEST,
  UNAUTHORIZED,
  FORBIDDEN,
  NOT_FOUND,
  METHOD_NOT_ALLOWED,
  INTERNAL_SERVER_ERROR,
};
